# Generated by Django 4.0.8 on 2022-11-07 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0001_initial'),
        ('users', '0002_phonenumbertype_user_address_line_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address_line_1',
            field=models.CharField(max_length=50, verbose_name='line 1'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(max_length=50, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='globals.state', verbose_name='state'),
        ),
        migrations.AlterField(
            model_name='user',
            name='zip_code',
            field=models.CharField(max_length=15, verbose_name='ZIP code'),
        ),
    ]
