# Generated by Django 4.0.8 on 2022-11-07 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('globals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created datetime')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated datetime')),
                ('slug', models.SlugField(unique=True)),
                ('address_line_1', models.CharField(max_length=50, verbose_name='line 1')),
                ('address_line_2', models.CharField(blank=True, max_length=50, verbose_name='line 2')),
                ('zip_code', models.CharField(max_length=15, verbose_name='ZIP code')),
                ('city', models.CharField(max_length=50, verbose_name='city')),
                ('all_tenants', models.ManyToManyField(related_name='%(app_label)s_%(class)s_all_tenants', to=settings.AUTH_USER_MODEL, verbose_name='all tenants')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_manager', to=settings.AUTH_USER_MODEL, verbose_name='manager')),
                ('responsible_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_responsible_user', to=settings.AUTH_USER_MODEL, verbose_name='responsible user')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='globals.state', verbose_name='state')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name_plural': 'properties',
            },
        ),
    ]
