# Generated by Django 4.0.8 on 2022-11-06 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('code', models.CharField(help_text="e.g., 'WA' for Washington", max_length=10, verbose_name='code')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
